In [2]:
from __future__ import print_function
import torch

In [4]:
x = torch.empty(5, 3) # Constract a 5 * 3 matrix, no initialize
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [5]:
x = torch.rand(5, 3) # Constract a 5 * 3 randon initialize matrix
print(x)

tensor([[0.6410, 0.9163, 0.7443],
        [0.2384, 0.2908, 0.7397],
        [0.1122, 0.6587, 0.6896],
        [0.0126, 0.0866, 0.4674],
        [0.5055, 0.8837, 0.3986]])


In [6]:
# Constract a 5 * 3 zero matrix, type is 'long'
x = torch.zeros(5, 3, dtype = torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [7]:
# Constract a tensor, with Initialize
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [9]:
# new_* methods take in sizes, Initial all tensor value is 1
x = x.new_ones(5, 3, dtype = torch.double)
print(x)

# override dtype!
x = torch.randn_like(x, dtype = torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.0321, -0.4978, -1.4302],
        [ 1.5756, -0.2376,  0.4610],
        [ 1.0698, -1.1333, -0.1500],
        [ 1.6854, -0.7553,  0.6403],
        [ 0.2546,  0.5491, -0.4972]])


In [10]:
# Get Dimension info
print(x.size())

torch.Size([5, 3])


In [13]:
# add manipulation
y = torch.rand(5, 3)
print(x + y) # method 1
print(torch.add(x, y)) # method 2

result = torch.empty(5, 3)
torch.add(x, y, out = result)
print(result) # method 3, let result = x + y

tensor([[ 0.0796, -0.2301, -0.5182],
        [ 2.5233, -0.1323,  0.4732],
        [ 2.0520, -0.9175,  0.2134],
        [ 1.9975,  0.2063,  1.1297],
        [ 1.2016,  0.9824,  0.4417]])
tensor([[ 0.0796, -0.2301, -0.5182],
        [ 2.5233, -0.1323,  0.4732],
        [ 2.0520, -0.9175,  0.2134],
        [ 1.9975,  0.2063,  1.1297],
        [ 1.2016,  0.9824,  0.4417]])
tensor([[ 0.0796, -0.2301, -0.5182],
        [ 2.5233, -0.1323,  0.4732],
        [ 2.0520, -0.9175,  0.2134],
        [ 1.9975,  0.2063,  1.1297],
        [ 1.2016,  0.9824,  0.4417]])


### 1. Any tensor manipulation will change tensor
#### ex. x.copy(y), x.t_() , will change x

### 2. Can use numpy like index manipulation on tensor

In [15]:
# Change tensor size or shape, can using "torch.view"
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8) # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [17]:
# Can get value on tensor
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.7360])
0.7359582185745239
